FROM mysql:latest

MAINTAINER workin.me lenxeon lenxeon@163.com

ENV MYSQL_ROOT_PASSWORD Sample09X#


ADD ./init/ /init/

#RUN service mysql restart


# RUN /init/init.sql

# # RUN service mysql restart
# RUN chmod +x /init/*.sh \
#   && /init/mysql-init.sh


# EXPOSE 3306

# RUN tail -f /*
