FROM apps/base

MAINTAINER workin.me lenxeon lenxeon@163.com

#ADD ./web-apps-id-service.war /usr/local/server/tomcat7/webapps

# ENV zookeeper.host zookeeper:2181
# ENV zookeeper.group /apps/config
# ENV zookeeper.version 1.0.002

# EXPOSE 8080
#RUN tail -f /*
