FROM dev/base

MAINTAINER workin.me lenxeon lenxeon@163.com

ADD ./app-commons-provider-1.0-SNAPSHOT-assembly.tar.gz /

# ENV zookeeper.host zookeeper:2181
# ENV zookeeper.group /apps/config
# ENV zookeeper.version 1.0.002

#EXPOSE 8080
#RUN tail -f /*
