nginx:
  build: ./nginx-node/
  ports:
    - "10080:80"
  # restart: always
  # command: /usr/local/server/openresty/nginx/sbin/nginx && while true;do sleep 60;done

tomcat_01:
  build: ./tomcat-node/
  # ports:
  #   - "10080:80"
  # restart: always
  # command: /usr/local/server/openresty/nginx/sbin/nginx && while true;do sleep 60;done

tomcat_02:
  build: ./tomcat-node/
  # ports:
  #   - "10080:80"
  # restart: always
  # command: /usr/local/server/openresty/nginx/sbin/nginx && while true;do sleep 60;done
