FROM apps/base

MAINTAINER workin.me lenxeon lenxeon@163.com

ENV CATALINA_HOME /usr/local/server/tomcat7
ENV PATH $PATH:$CATALINA_HOME/bin


#ADD ucenter-user-provider-1.0-SNAPSHOT-assembly.tar.gz /



EXPOSE 8080
RUN tail -f /*
