FROM apps/base

MAINTAINER workin.me lenxeon lenxeon@163.com

#ADD ./app-commons-provider.tar.gz /

# ENV zookeeper.host zookeeper:2181
# ENV zookeeper.group /apps/config
# ENV zookeeper.version 1.0.002

#EXPOSE 8080
# RUN cd /app-commons-provider-1.0-SNAPSHOT && java -jar app-commons-provider-1.0-SNAPSHOT.jar &
